complete -c lamp -n "__fish_use_subcommand" -s s -l set -d 'Sets brightness to given value'
complete -c lamp -n "__fish_use_subcommand" -s i -l increase -d 'Increases brightness'
complete -c lamp -n "__fish_use_subcommand" -s d -l decrease -d 'Decreases brightness'
complete -c lamp -n "__fish_use_subcommand" -s t -l type -d 'choose controller type' -r -f -a "raw lin log"
complete -c lamp -n "__fish_use_subcommand" -s g -l get -d 'Prints current brightness value'
complete -c lamp -n "__fish_use_subcommand" -s z -l zero -d 'Sets brightness to lowest value'
complete -c lamp -n "__fish_use_subcommand" -s f -l full -d 'Sets brightness to highest value'
complete -c lamp -n "__fish_use_subcommand" -s l -l list -d 'Lists all available brightness and led controllers'
complete -c lamp -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c lamp -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
